#include <stdio.h>
#include <unistd.h>
#include <sgx_urts.h>
#include "Enclave/Enclave_u.h"  // generated by edger8r tool

#define ENCLAVE_PATH "Enclave/enclave.signed.so"

void
ocall_print(const char* msg)
{
    printf("%s", msg);
}

void
usage(const char *cmd)
{
    fprintf(stderr, "%s: -s|-u [ -i <input file path> ] [ -o <output file path> ]\n", cmd);
    exit(-1);
}

void
dump(const char *msg, const unsigned char *bf, int size)
{
    int	i;
    printf("%s", msg);
    for (i = 0; i < size; i++) {
	printf("%02x:", bf[i]);
    }
    printf("\n");
}

int	sflag = 0;
int	uflag = 0;
int	mflag = 0;
char	*ipath = NULL;
char	*opath = NULL;

int
main(int argc, char **argv)
{
    FILE	*ifp = NULL;
    FILE	*ofp = NULL;
    sgx_enclave_id_t	eid = 0;
    sgx_launch_token_t	token = {0};
    sgx_status_t	st;
    int		updated = 0;
    size_t	len, rlen;
    uint8_t	*bufp;
    int	rc;

    while ((rc = getopt(argc, argv, "sui:o:")) != -1) {
	switch(rc) {
	case 's': /* seal */
	    sflag = 1; break;
	case 'u': /* unseal */
	    uflag = 1; break;
	case 'i': /* input file path */
	    ipath = strdup(optarg); break;
	case 'o': /* output file path */
	    opath = strdup(optarg); break;
	}
    }
    if (sflag & uflag || (!sflag & !uflag)) {
	usage(argv[0]);
	/* never returns */
    }
    if (!ipath) {
	ipath = strdup(sflag == 1 ? "plaindata.txt" : "encdata.txt");
    }
    ifp = fopen(ipath, "r");
    if (ifp == NULL) {
	fprintf(stderr, "Cannot open file: %s\n", ipath);
	exit(-1);
    }
    fseek(ifp, 0, SEEK_END);
    len = ftell(ifp);
    rewind(ifp);

    bufp = malloc(len);
    if (!bufp) {
	fprintf(stderr, "Cannot allocate memory size=%ld\n", len);
	exit(-1);
    }
    rlen = fread(bufp, 1, len, ifp);
    if (rlen != len) {
	fprintf(stderr, "Cannot allocate memory size=%ld\n", len);
	exit(-1);
    }
    
    if (opath) {
	ofp = fopen(opath, "w");
    } else {
	ofp = (sflag == 1) ? fopen("encdata.txt", "w") : stdout;
    }
    if (ofp == NULL) {
	fprintf(stderr, "Cannot open file: %s\n", opath);
	exit(-1);
    }

    st = sgx_create_enclave(ENCLAVE_PATH, SGX_DEBUG_FLAG,
			    &token, &updated, &eid, NULL);
    if (st != SGX_SUCCESS) {
        printf("sgx_create_enclave failed: 0x%x\n", st);
        return 1;
    }

    if (uflag) {
	uint8_t	outd[1024];
	uint32_t	len_out = 1024;
	uint32_t	msz = -1;
	uint32_t	psz = -1;
	printf("Unsealing %s --> %s\n", ipath, opath);
	memset(outd, 0, sizeof(outd));
	ecall_unseal(eid, &st, len, bufp, len_out, outd, &psz);
	printf("st = %d msz = %d psz = %d\n", st, msz, psz);
	fwrite(outd, 1, psz, ofp);
    } else {
	uint8_t	outd[1024];
	uint32_t	len_out = 1024;
	uint32_t	encsz = -1;
	printf("Sealing %s --> %s\n", ipath, opath);
	ecall_seal(eid, &st, len, bufp, len_out, outd, &encsz);
	printf("st = %d encsz = %d\n", st, encsz);
	fwrite(outd, 1, encsz, ofp);
    }

    if (ipath) free(ipath);
    if (opath) free(opath);
    if (ifp) fclose(ifp);
    if (ofp) fclose(ofp);
    sgx_destroy_enclave(eid);
    return 0;
}
